logging errors

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -25,11 +25,18 @@ jobs:
 
             LIB_LIST=$(find ./instrumentation -name go.mod -exec dirname {} \;)
 
+            PPWWDD=$(echo "$PWD")
+
             echo "will attempt to cover instapgx"
-            cd "./instrumentation/instapgx" && go mod tidy && go test -v -tags=integration -coverpkg=./... -cover -covermode atomic -coverprofile coverage.out ./... -json > coverage.json && cd ../../
+            cd ./instrumentation/instapgx
+            go mod tidy || echo "failed on mod tidy"
+            go test -v -tags=integration -coverpkg=./... -cover -covermode atomic -coverprofile coverage.out ./... -json > coverage.json || echo "fail on go test"
+            cd ../../
             echo "after attempt to cover instapgx"
 
             echo "current directory is $PWD"
+
+            cd $PPWWDD
 
             for lib in $LIB_LIST
               do cd "$lib" && go mod tidy && go test -v -coverpkg=./... -cover -covermode atomic -coverprofile coverage.out ./... -json > coverage.json && cd -;
